name: Preconfiguration

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:

  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  setup-gtest:
    # Name the Job
    name: Setup Google Test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Download sources
        run: sudo apt install googletest
      - name: Build GTest
        run: cd /usr/src/googletest; sudo cmake .; make -j4
      - name: Install GTest
        run: cd /usr/src/googletest; sudo make install
